number=eval(input('请输入一个四位数'))
print('千位数是：',number//1000)
print('百位数是：',number//100%10)
print('十位数是：',number%100//10)
print('个位数是：',number%10)

number=(input('请输入一个四位数'))
print('千位数是：',number[0])
print('百位数是：',number[1])
print('十位数是：',number[2])
print('个位数是：',number[3])

father_heigh=eval(input('请输入父亲身高'))
monther_heigh=eval(input('请输入母亲身高'))
print('儿子的身高是：',((father_heigh+monther_heigh)*0.54))